---
on: push

permissions:
  contents: read

jobs:
  code-inspection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up python
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[code-inspection]

      - name: Run pylint
        run: pylint rundetection test

      - name: Run MyPy
        run: mypy --strict rundetection
